# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analise.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analise.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ranalise.proto\x12\x07\x61nalise\"[\n\rPedidoAnalise\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\x0c\n\x04zona\x18\x02 \x01(\t\x12\x11\n\tsensor_id\x18\x03 \x01(\t\x12\x0e\n\x06inicio\x18\x04 \x01(\t\x12\x0b\n\x03\x66im\x18\x05 \x01(\t\"\xa8\x01\n\x10ResultadoAnalise\x12\r\n\x05media\x18\x01 \x01(\x01\x12\x0e\n\x06maximo\x18\x02 \x01(\x01\x12\x0e\n\x06minimo\x18\x03 \x01(\x01\x12\x15\n\rdesvio_padrao\x18\x04 \x01(\x01\x12\x13\n\x0bnivel_risco\x18\x05 \x01(\t\x12\x11\n\ttendencia\x18\x06 \x01(\t\x12\x16\n\x0etotal_medicoes\x18\x07 \x01(\x05\x12\x0e\n\x06resumo\x18\x08 \x01(\t2T\n\x0e\x41naliseService\x12\x42\n\rAnalisarDados\x12\x16.analise.PedidoAnalise\x1a\x19.analise.ResultadoAnaliseB\x11\xaa\x02\x0eServicoAnaliseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analise_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016ServicoAnalise'
  _globals['_PEDIDOANALISE']._serialized_start=26
  _globals['_PEDIDOANALISE']._serialized_end=117
  _globals['_RESULTADOANALISE']._serialized_start=120
  _globals['_RESULTADOANALISE']._serialized_end=288
  _globals['_ANALISESERVICE']._serialized_start=290
  _globals['_ANALISESERVICE']._serialized_end=374
# @@protoc_insertion_point(module_scope)
